In [182]:
import numpy as np
import matplotlib.pyplot as plt

In [183]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [184]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
a.shape

(3, 3)

In [186]:
a.ndim

2

In [187]:
a.size

9

In [188]:
a.dtype

dtype('int32')

In [189]:
a.itemsize

4

In [190]:
type(a[1][1])

numpy.int32

In [191]:
a.dtype.name

'int32'

In [192]:
a = np.array([1,2,3,4], dtype = np.complex)
a.dtype

dtype('complex128')

In [193]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [194]:
a = np.ones((3,2), dtype = np.int32)
a

array([[1, 1],
       [1, 1],
       [1, 1]])

In [195]:
np.empty((2,2,2))

array([[[1., 0.],
        [2., 0.]],

       [[3., 0.],
        [4., 0.]]])

In [196]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [197]:
np.arange(1,2,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

In [198]:
np.linspace(0,3,6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. ])

In [199]:
x = np.linspace(0, 2 * pi, 100)

NameError: name 'pi' is not defined

In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([8,7,6,5])
b-a

array([7, 5, 3, 1])

In [ ]:
b+a

array([9, 9, 9, 9])

In [ ]:
a*b

array([ 8, 14, 18, 20])

In [ ]:
a/b

array([0.125     , 0.28571429, 0.5       , 0.8       ])

In [ ]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,2],[1,2]])

In [ ]:
a@b

array([[ 5,  6],
       [13, 14]])

In [ ]:
a.dot(b)

array([[ 5,  6],
       [13, 14]])

In [ ]:
a = np.array([[1,2],[3,4]],dtype=np.int32)
b = np.array([[3,2],[1,2]],dtype=np.float64)
c = a + b
c.dtype

dtype('float64')

In [ ]:
a = np.random.random((2,3))
a

array([[0.09291709, 0.36686894, 0.88096043],
       [0.20985186, 0.1433596 , 0.67468045]])

In [ ]:
a.min()

0.09291709064299836

In [ ]:
a.max()

0.8809604347992017

In [ ]:
a.sum()

2.3686383681150147

In [ ]:
a.mean()

0.39477306135250245

In [ ]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [ ]:
a.max(axis=1)

array([ 3,  7, 11])

In [ ]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [ ]:
np.add(a,a)

array([0, 2, 4, 6])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[3]

3

In [ ]:
a[2:8]

array([2, 3, 4, 5, 6, 7])

In [ ]:
a[::3]

array([0, 3, 6, 9])

In [ ]:
for i in a:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [ ]:
def f(x, y):
    return 5*x+y


In [ ]:
a = np.fromfunction(f,(4,4),dtype = np.int64)
a

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]], dtype=int64)

In [ ]:
a[3,2]

17

In [ ]:
a[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]], dtype=int64)

In [ ]:
a[1][-1]

8

In [ ]:
for row in a:
        print(row)

[0 1 2 3]
[5 6 7 8]
[10 11 12 13]
[15 16 17 18]


In [ ]:
for elm in a.flat:
    print(elm,end=" ")

0 1 2 3 5 6 7 8 10 11 12 13 15 16 17 18 

In [ ]:
a = np.random.randint(8,size=(2,4))
a

array([[3, 7, 7, 5],
       [6, 6, 1, 7]])

In [ ]:
a.shape

(2, 4)

In [ ]:
a.ravel()

array([3, 7, 7, 5, 6, 6, 1, 7])

In [ ]:
a.flatten()

array([3, 7, 7, 5, 6, 6, 1, 7])

In [ ]:
a.T

array([[3, 6],
       [7, 6],
       [7, 1],
       [5, 7]])

In [ ]:
a.resize((2,4))
a

array([[3, 7, 7, 5],
       [6, 6, 1, 7]])

In [ ]:
a.reshape(1,8)

array([[3, 7, 7, 5, 6, 6, 1, 7]])

In [ ]:
a

array([[3, 7, 7, 5],
       [6, 6, 1, 7]])

In [ ]:
a = np.random.randint(1000,size = (10*100))
b=a.reshape(25,-1)
b.shape

(25, 40)

In [ ]:
a = np.zeros((2,2))
b = np.ones((2,2))

In [ ]:
np.vstack((a,b))

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.hstack((a,b))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [ ]:
a = np.zeros((1,2))
b = np.ones((1,2))

In [ ]:
np.column_stack((a,b))

array([[0., 0., 1., 1.]])

In [ ]:
np.hstack((a,b))

array([[0., 0., 1., 1.]])

In [ ]:
a = np.random.randint(20,size=(2,10))
a

array([[17,  0,  4, 16,  0, 11,  1,  0,  7,  7],
       [ 8,  9,  4,  0, 15,  5, 16,  3,  1, 16]])

In [ ]:
np.hsplit(a,2)

[array([[17,  0,  4, 16,  0],
        [ 8,  9,  4,  0, 15]]),
 array([[11,  1,  0,  7,  7],
        [ 5, 16,  3,  1, 16]])]

In [ ]:
np.hsplit(a,(2,5))

[array([[17,  0],
        [ 8,  9]]),
 array([[ 4, 16,  0],
        [ 4,  0, 15]]),
 array([[11,  1,  0,  7,  7],
        [ 5, 16,  3,  1, 16]])]

In [ ]:
a = np.random.randint(48,size=(6,8))
a

array([[29, 14, 16, 44, 35,  4, 13, 18],
       [12, 31, 15,  6, 12, 45,  3, 41],
       [28, 11, 29,  3, 31, 20, 29, 41],
       [30,  1, 21, 21, 13,  2, 45,  6],
       [43, 47,  0, 41, 41, 23, 38, 38],
       [16,  3, 18, 28, 43, 45, 38,  1]])

In [ ]:
np.vsplit(a,2)

[array([[29, 14, 16, 44, 35,  4, 13, 18],
        [12, 31, 15,  6, 12, 45,  3, 41],
        [28, 11, 29,  3, 31, 20, 29, 41]]),
 array([[30,  1, 21, 21, 13,  2, 45,  6],
        [43, 47,  0, 41, 41, 23, 38, 38],
        [16,  3, 18, 28, 43, 45, 38,  1]])]

In [ ]:
np.array_split(a,(2,5),axis=0)

[array([[29, 14, 16, 44, 35,  4, 13, 18],
        [12, 31, 15,  6, 12, 45,  3, 41]]),
 array([[28, 11, 29,  3, 31, 20, 29, 41],
        [30,  1, 21, 21, 13,  2, 45,  6],
        [43, 47,  0, 41, 41, 23, 38, 38]]),
 array([[16,  3, 18, 28, 43, 45, 38,  1]])]

In [ ]:
a = np.array([[1,2],[3,4]])
b = a
b is a

True

In [ ]:
b[0]

array([1, 2])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = a.view()
c

array([[1, 2],
       [3, 4]])

In [ ]:
c is a

False

In [ ]:
c.base is a

True

In [ ]:
c = c.reshape((1, 4))
c.shape 

(1, 4)

In [ ]:
a.shape

(2, 2)

In [ ]:
c[0,0]=666
a

array([[666,   2],
       [  3,   4]])

In [ ]:
d = a.copy()
d is a

False

In [ ]:
d.base is a

False

In [ ]:
d[0][0] = 999
a

array([[666,   2],
       [  3,   4]])

In [200]:
e = a[:,1].copy()
del a


In [201]:
a = np.array([[ 0, 0, 0],[10,10,10]])
b = np.array([1,2,3])
a+b

array([[ 1,  2,  3],
       [11, 12, 13]])

In [205]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [207]:
index = np.array([1,3,4,6])
a[index]

array([ 1,  9, 16, 36], dtype=int32)

In [208]:
j = np.array([[3, 4], [9, 7]])
a[j] 

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [209]:
a = np.arange(12).reshape(3,4)

In [210]:
b = a > 6

In [211]:
b

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [212]:
a[b]

array([ 7,  8,  9, 10, 11])

In [214]:
a = np.array([5,4,1,2,7,9,3,6,0])
a

array([5, 4, 1, 2, 7, 9, 3, 6, 0])

In [215]:
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [216]:
np.argsort(a)

array([8, 2, 3, 6, 1, 0, 7, 4, 5], dtype=int64)

In [217]:
a = np.arange(10)

In [218]:
a[a>5]

array([6, 7, 8, 9])

In [220]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [221]:
np.insert(a,1,999,axis=1)

array([[  1, 999,   2,   3,   4],
       [  5, 999,   6,   7,   8],
       [  9, 999,  10,  11,  12]])

In [224]:
np.delete(a,[1],axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])